# This rule is not used by the project redis-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the ivangonzalezacuna.docker.io.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: redis-operator
    app.kubernetes.io/managed-by: kustomize
  name: redisoperator-editor-role
rules:
- apiGroups:
  - ivangonzalezacuna.docker.io
  resources:
  - redisoperators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ivangonzalezacuna.docker.io
  resources:
  - redisoperators/status
  verbs:
  - get
